version: '3'

services:
    web:
        image: nginx:latest
        container_name: hsb_web
        ports:
            - '${HTTP_PORT:-80}:80'
        depends_on:
            - php
        volumes:
            - .:/hsb-website
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        restart: always

    php:
        container_name: hsb_php
        build:
            context: ./docker/php
        depends_on:
            - composer
        volumes:
            - .:/hsb-website
        restart: always

    composer:
        container_name: hsb_composer
        build:
            context: ./docker/composer
        command: install --ignore-platform-reqs
        volumes:
            - .:/app
        restart: 'no'
